services:
  web:
    build:
      context: 'https://github.com/miuguelt/fincaFront-main.git'          
      dockerfile: Dockerfile
    image: nginx:alpine 
    ports:
      - "80:80"            
    restart: always
    depends_on:
      - backend